### ISSUE TITLE
自苗問題

### ISSUE THREAD

**Issue by azubu23202869** [xuaii/auto-aim-fps-games#1]
他不受控制的亂打，想問一下相關環境建置，以及模型訓練

**Comment by xuaii** [comment]
这需要调整 .py 文件中的参数并关闭鼠标加速度
FOV：需要真实fov，例如游戏内的110的真实fov是123.26（可以在 https://www.mouse-sensitivity.com/查询）
SENS：游戏内灵敏度
ADS：各个倍镜的ADS

如果参数设置没有问题，还不能瞄准可能是因为：
当检测到屏幕上的目标并移动鼠标后会开始下一帧检测，但是因为鼠标移动可能会有延迟，这会导致下一帧捕获到的图像还未更新准星位置，所以重复移动准星。将 config.json 中 mouseMovementDelay 调高会改善此问题。

Tensorrt 的环境依赖：
1. opencv4.6
2. cuda11.5
3. cuDNN 11.3.58
4. tensorrt 8.2.5.1
ncnn 的环境被我删了。。我也忘记版本了，tensorrt版本对cuda和cudnn的依赖很严格，不同版本导出的 .rt 模型文件都是不兼容的，所以要自己训练模型的话需要保持版本一致。哦，模型训练、导出、转换都是按照yolov7 的官方repo做的。

**Comment by xuaii** [comment]
> 

我会上传一个带 UI 的版本，可以查看能否在画面中检测到敌人，以方便调参数

**Comment by azubu23202869** [comment]
感謝說明非常簡單明瞭，也祝您考研順利一定上榜
