### ISSUE TITLE
Can't change process name

### ISSUE THREAD

**Issue by Ternimus87** [xuaii/auto-aim-fps-games#2]
https://github.com/xuaii/auto-aim-fps-games/blob/ef5572d04c1433847ce7a8f88a5fb72fe8fc30ad/AutoAim-ncnn/inference.cpp#L33

This should be config.windowName and not "Apex Legends"

**Comment by xuaii** [comment]
> https://github.com/xuaii/auto-aim-fps-games/blob/ef5572d04c1433847ce7a8f88a5fb72fe8fc30ad/AutoAim-ncnn/inference.cpp#L33
> 
> 
> 
> This should be config.windowName and not "Apex Legends"

 Thank you,I will modify the code.
